### ISSUE TITLE
Nov 24 2020 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/open-regtech-sig#10]
# Regulation Innovation SIG
## Date
Nov 24 2020 - 12pm EST / 5pm GMT

## Untracked attendees
- Adam Hurwitz / Microsoft
- Antonio Ponte / Citi
- Beeke-Marie Nelke / GS
- Bruno Domingues / Intel
- Craig Rowe / Cantor Fitzgerald
- David Ehrich / AIR
- Edo de Vries Robbe / Arachnys
- Elena Sparks / JP Morgan
- Ian Hollowbread / ING
- Ian Purvis / Openfin
- Sarah Jankowski / GS
- Erwin Jean Louis / GS
- Jim Wang / Regnosys
- Lawrence Drake / JP Morgan
- Matt Gracie / Deloitte
- Nicolas Decouttere / Barclays
- Robin Weiss / Fidelity
- Simon Holt / JP Morgan
- Vishal Kapur / Deloitte

## Agenda
- [x] Convene & roll call
- [x] Approve [November 10th meeting minutes](https://github.com/finos/open-regtech/issues/2) - _meeting minutes were approved_ 
- [x] Potential to get better open source standards around regulatory data:  Industry Example MS Morphir (8 min)
- [x] How can we improve Regulatory Reporting:  Industry example: Regnosys CDM (8 min)
- [x] The need for a Regulatory Taxonomy / ontology – How solutions can benefit from more standards: Industry example RegExplorer (15 min)
- [ ] AOB, Q&A & Adjourn (5mins)

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=mc39f602c94618d58437eac6707b6b5ab
- Meeting number: 127 988 1411
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 988 1411

**Comment by mvanbuskirk** [comment]
Here

**Comment by nigelcobb** [comment]
here

**Comment by anelledavis** [comment]
here

**Comment by pmhunter** [comment]
Here

**Comment by melissakahlke** [comment]
here

**Comment by adamj-codethink** [comment]
Hello o/

**Comment by lolabeis** [comment]
Here (but horrible phone connection)

**Comment by grill1002** [comment]
here

**Comment by johnmark** [comment]
howdy - here

**Comment by catethompson** [comment]
here

**Comment by nigelcobb** [comment]
Additional materials related to Rosetta solution.
G20 techsprint submission - https://github.com/rosetta-models/g20-tech-sprint
Solution demonstration - https://vimeo.com/453260500

**Comment by brooklynrob** [comment]
Here. As mentioned, if you'd like an account on the FINOS shared instance of [Legend](legend.finos.org/studio) (in which there is a copy of the CDM), fill out the form at the bottom of https://www.finos.org/legend and we'll get you set up.

**Comment by pbouda** [comment]
here too

**Comment by minesh-s-patel** [comment]
Here

**Comment by stephengoldbaum** [comment]
Ciao.
https://github.com/finos/morphir-examples/tree/master/src/Morphir/Sample/LCR
