### ISSUE TITLE
Dec 8th 2020 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/open-regtech-sig#13]
# Regulation Innovation SIG
## Date
Dec 8th 2020 - 12pm EST / 5pm GMT

## Untracked attendees
- Craig Rowe / Cantor Fitzgerald
- David Ehrich / AIR
- Ian Hollowbread / ING
- Jo Ann Barefoot / AIR
- Neil Slinger / JP Morgan
- Richard Maton / Aperio
- Salwa Fassi / SMBC
- Stephen Goldbaum / Morgan Stanley
- Taniem Choudhury / Deutsche Bank

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes - _[November 24th meeting minutes](https://github.com/finos/open-regtech/issues/10) were approved_
- [x] An AppStore to find and consume pre-validated RegTech solutions. Example: Orchestrate  (5-10 min)
- [x] The need for a Regulatory Taxonomy / ontology – How solutions can benefit from more standards. Example: Apiax (5-10 min)
- [x] Discussion: drill down on focus areas. **_Please come prepared to raise 1-2 issues that you think the group should or could address through open collaboration (i.e. leveraging or producing open source software or standards)_** 
    - Goal of the SIG is to identify projects that this group would like to work on, and parties committed to contributing ideas and resources to this project
    - content driven projects (content areas TBD) 
    - infrastructure driven (data standards, API, taxonomy/ontology, data & domain models)
    - importance to identify specific use cases
- [x] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ] Create list of potential focus areas, use cases, and tools that may be leveraged to collaborate on reg-related topics in the open

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=mc39f602c94618d58437eac6707b6b5ab
- Meeting number: 127 988 1411
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 988 1411

**Comment by TLATER** [comment]
o/

**Comment by toshaellison** [comment]
Present

**Comment by mvanbuskirk** [comment]
Present

**Comment by brooklynrob** [comment]
Here.

**Comment by mcleo-d** [comment]
Hello Reg SIG 👋

**Comment by adamj-codethink** [comment]
![tenor](https://user-images.githubusercontent.com/45950887/101516734-bd9ce680-3977-11eb-8f9a-5c17e1949bca.gif)

**Comment by anelledavis** [comment]
Present.

**Comment by jim-h-wang** [comment]
Present

**Comment by junjikatto** [comment]
Hi!

**Comment by srholt62** [comment]
joined (only on for first 40mins) and I am hoping we may be joined by Sam O'Neill our MD in charge of regulatory strategy

**Comment by anelledavis** [comment]
Apologies. Have to leave early, but look forward to reading over the minutes and hearing ideas for collaboration.

**Comment by pbouda** [comment]
I am here
