### ISSUE TITLE
Jan 5th 2021 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/open-regtech-sig#14]
# Regulation Innovation SIG
## Date
January 5th 2021 - 12pm EST / 5pm GMT

## Untracked attendees
- Christopher Trepel / Lowell
- David Ehrich / AIR 
- Junji Katto / Itau
- Paula Hunter / Mojaloop
- Richard Maton / Aperio
- Taniem Choudhury / DB

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [ ] Approve [December 8th meeting minutes](https://github.com/finos/open-regtech/issues/13)
- [x] **Discuss and prioritize the proposed projects that have been presented in previous meetings**. Topics/ projects the group has found interesting so far, and new projects that could be considered:

    - Using **Rosetta** to address challenges around tax reporting 
    
    - **CDM regulatory use cases using morphir**: making definitions work for every type of product by starting from the business logic as opposed to the definition (opposite approach to the same problem)
    
    - Consistent, industry-wide **ontology** (along the lines of the Apiax presentation) applied to a specific scope (i.e. Basel III, FRTB)
        - Taniem Choudhury volunteered to start gathering a list of regulations that could be of interest (see "Action items" section). A next step would be for the group to identify ontologies that could be reused or built upon
        - Participants highlighted the importance of defining specific tools, lineage, being able to compare the solutions that every system/ process yields
        
    - Creating a **tool-agnostic, standard Open Source regulatory messaging platform**. Financial institutions could easily adopt this OS standard and have an assurance that it can be reported accurately. A next step would be the development of tools that meet this standard.
    
    - **AML**:
        - potential use cases around US National Defense Authorization Act and/or FINCEN Beneficial Ownership Databases.
        - developing and sharing typologies, optimizing algorithms, enabling those to be shared & optimized. creating services collectively in any shape or form
        
    - **Legend**: data models, data modeling agenda
    
- Other comments/ concerns: it was discussed whether Regulators should be included in the conversation. It would be ideal to engage regulators and to receive endorsement from regulators

- [x] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ] Taniem Choudhury (DB) to start a thread (either on GitHub or via open-regtech-sig@finos.org) to gather a list of relevant regulations & regulators 
- [ ] David Ehrich (AIR) & FINOS to create and circulate an **overview document with brief descriptions of projects/ tools presented at Reg SIG meetings to date**
- [ ] ALL to contribute specific use cases around building ontologies

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=mc39f602c94618d58437eac6707b6b5ab
- Meeting number: 127 988 1411
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 988 1411

**Comment by toshaellison** [comment]
Here

**Comment by stephengoldbaum** [comment]
Here

**Comment by mvanbuskirk** [comment]
Here

**Comment by anelledavis** [comment]
Here

**Comment by cr20ro20** [comment]
Hi from Craig Rowe (Cantor Fitzgerald)

**Comment by mkuchibhotla** [comment]
Present. My first meeting here.

**Comment by pmhunter** [comment]
Paula Hunter, Mojaloop here, shifting from phone to webex.

**Comment by ffionwiggins** [comment]
Here (GS) - and Adam Turnbull will be joining future sessions

**Comment by nigelcobb** [comment]
present

**Comment by pbouda** [comment]
here

**Comment by jpmsrh** [comment]
hi Simon and also Sam O'Neill (MD for Reg Risk Reporting Strategy) joined from JPMC.  Note contacts simon.r.holt@jpmorgan.com &  sam.e.oneill@jpmorgan.com

**Comment by stephengoldbaum** [comment]
Here (stephen.goldbaum@morganstanley.com)

**Comment by jim-h-wang** [comment]
Present. 

@David, @toshaellison, @aitana16, Thank you for the engaging session earlier today. I would like to register REGnosys’ interest in the following themes raised in the meeting:

* **Open sourced, standardised and executable regulatory rule logic.** Encoding regulatory rule logic in a human readable and machine executable format has been and continues to be a main focus for REGnosys. As we continue to partner with ISDA in adding such rule logic into CDM, it would be of particular interest if anyone in this group to evaluate viability of CDM and our tooling.
* **Interoperability of technical tooling.** No single software provider offers the full end-to-end solution. Interoperability of tooling, based on a common abstraction layer like Morphir, would benefit market participants by allowing them to select best in class solutions more granularly, which also reduces vendor lock-in risk.
