### ISSUE TITLE
Feb 2nd 2021 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/open-regtech-sig#19]
# Regulation Innovation SIG
## Date
Feb 2nd 2021 - 12pm EST / 5pm GMT

## Untracked attendees
- Adam Jones / Codethink
- Aitana Myohl / FINOS
- Craig Rowe / Cantor Fitzgerald
- David Ehrich / AIR 
- Gil Yehuda / US Bank
- Ian Hollowbread / ING
- Paula Hunter / Mojaloop
- Peter Bouda / Apiax
- Renato Menna / Deutsche Bank
- Sam O'Neill / JP Morgan
- Stephen Goldbaum / Morgan Stanley
- Taniem Choudhoury / Deutsche Bank
- Tosha Ellison / FINOS

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve [January 19th meeting minutes](https://github.com/finos/open-regtech-sig/issues/16)
- [x] Review [projects and use cases proposed so far](https://github.com/finos/open-regtech-sig/issues/17 ) and agree on specific projects to pursue 
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] A decision was made for participants to regroup in smaller, use-case focused groups to discuss potential projects

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=mc39f602c94618d58437eac6707b6b5ab
- Meeting number: 127 988 1411
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 988 1411

**Comment by mvanbuskirk** [comment]
Here

**Comment by anelledavis** [comment]
Here

**Comment by nigelcobb** [comment]
here
