### ISSUE TITLE
March 2nd 2021 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/open-regtech-sig#21]
# Regulation Innovation SIG
## Date
March 2nd 2021 - 12pm EST / 5pm GMT

## Untracked attendees
- Aaron Shiret / Bank of England
- David Ehrich / AIR 
- Ffion Acland / GS
- Ian Hollowbread / ING
- Jo Ann Barefoot / AIR
- Lee McGouran / Morgan Stanley
- Nigel Cobb / Regnosys
- Oliver Buckley Salmon / Deutsche Bank
- Renato Menna / Deutsche Bank
- Richard Maton / Aperio Strategy
- Taniem Choudhury / Deutsche Bank

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve [Feb 2nd Meeting Minutes](https://github.com/finos/open-regtech-sig/issues/19) - _Meeting minutes were approved_
- [x] [FDC3](https://fdc3.finos.org) Demo - Riko Eksteen
- [x] [DRR collaboration use case proposal](https://github.com/finos/open-regtech-sig/files/6070764/FINOS.Reporting.Interoperability.Flow.Diagram.1.pdf) - Jim Wang
- [x] Proposal: move meeting to monthly cadence - _The meeting was moved to a monthly cadence_
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- The meeting was moved to a monthly cadence

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=mc39f602c94618d58437eac6707b6b5ab
- Meeting number: 127 988 1411
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 988 1411

**Comment by rikoe** [comment]
present

**Comment by toshaellison** [comment]
Here

**Comment by mikejstevenson** [comment]
Present

**Comment by agitana** [comment]
hi!

**Comment by pmhunter** [comment]
Present.

**Comment by gyehuda** [comment]
Hello nice people!

**Comment by anelledavis** [comment]
Present.

**Comment by stephengoldbaum** [comment]
present

**Comment by jim-h-wang** [comment]
Present.

**Comment by cr20ro20** [comment]
Hi from Craig Rowe

**Comment by martinudy** [comment]
Present

**Comment by aarshir** [comment]
present
