### ISSUE TITLE
April 6th 2021 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/open-regtech-sig#24]
# Regulation Innovation SIG
## Date
April 6th, 2021 - 12pm EST / 5pm GMT

## Untracked attendees
- Anand Satchit / Wells Fargo
- Ian Hollowbread / ING
- Ivan Radovanovic / Citizens Bank
- James Nicholls / Braithwate
- Nils Cluzel / Braithwate
- Richard Maton / Aperio Strategy

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve [March 2nd meeting minutes](https://github.com/finos/open-regtech-sig/issues/21) - _meeting minutes were approved_
- [x] Review [use cases, tools and potential projects](https://github.com/finos/open-regtech-sig/issues/17#issuecomment-770087776), identify volunteer project leads to launch specific projects
- [x] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ] Ian Hollowbread (ING): report back with updates on Orchestrate at the next meeting
- [ ] Nigel Cobb (Regnosys) & Stephen Goldbaum (Morgan Stanley): report back on EMIR Refit updates at the next meeting
- [x] James Nicholls (Braithwate) to share additional information on Taxonomy/Ontology projects at the next meeting
    - see James' proposal [Regulatory Taxonomy and Ontology Development](https://github.com/finos/open-regtech-sig/blob/master/resources/demo-summaries.md)
- [ ] James McLeod (FINOS) to set up Reg SIG Slack channel and share details with Reg SIG leads 

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=mc39f602c94618d58437eac6707b6b5ab
- Meeting number: 127 988 1411
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 988 1411

**Comment by DavidVtFreshAIR** [comment]
David is here

**Comment by mvanbuskirk** [comment]
Matt is here

**Comment by agitana** [comment]
hi!

**Comment by MahiraMohtashami** [comment]
Mahira Mohtashami - new attendee

**Comment by stephengoldbaum** [comment]
ciao

**Comment by toshaellison** [comment]
here

**Comment by nigelcobb** [comment]
here

**Comment by mcleo-d** [comment]
Hello everyone 👋

**Comment by bstone-suse** [comment]
Hello all.

**Comment by mcleo-d** [comment]
Thanks everyone for allowing my updates today. You're more than welcome to join the next [DevOps Mutualization meeting on Thursday 15 April 2021 - 12pm EST / 5pm UK](https://github.com/finos/devops-mutualization/issues/20) to understand the synergy that's forming across both SIGs.

You're also welcome to join the FINOS Community Slack by following the simple instructions here ... https://github.com/finos/community/#join-the-finos-slack

All the best,

James 🚀
