### ISSUE TITLE
May 4th 2021 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/open-regtech-sig#25]
# Regulation Innovation SIG
## Date
May 4th 2021 - 12pm EST / 5pm GMT

## Untracked attendees
- Andrew Stuart / Amex
- Blaine Stone / Suse
- David Ehrich / AIR
- Ian Hollowbread / ING
- James Nicholls / Braithwate
- Nicolas Decouttere / Regnosys
- Nils Cluzel / Braithwate
- Richard Maton / Aperio Strategy
- Samuel Meehan / Change Gap
- Sarah Sinclair / Change Gap
- Steve Grill / Fintech Studios
- Steven Beerh / Change Gap

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve [April 6th Meeting minutes](https://github.com/finos/open-regtech-sig/issues/24) - _meeting minutes were approved_
- [x] Proposed project: [Regulatory Taxonomy and Ontology Development](https://github.com/finos/open-regtech-sig/blob/master/resources/demo-summaries.md#regulatory-taxonomy-and-ontology-development) (Sarah Sinclair & James Nicholls)
- [x] Update on other potential projects:
    - [x] FDC3 Extension for RegTech (@ianhollowbread )
    - [x] SDLC / DevOps Mutualization (@mcleo-d)
- [x] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ] FINOS to promote Taxonomy & Ontology project proposal
- [ ] 
### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=mc39f602c94618d58437eac6707b6b5ab
- Meeting number: 127 988 1411
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 988 1411

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by gyehuda** [comment]
Hello all!

**Comment by stephengoldbaum** [comment]
Hello

**Comment by Ivan-Radovanovic** [comment]
hello

**Comment by anelledavis** [comment]
Here - hello!

**Comment by agitana** [comment]
hi!

**Comment by toshaellison** [comment]
Here! (Tosha Ellison, FINOS)

**Comment by TLATER** [comment]
o/

**Comment by Arilova** [comment]
Hello,
RANDRIAMIADANA Zakasoa Arilova (University of Antananarivo, Madagascar)

**Comment by alvin-c-shih** [comment]
Howdy!

I'm not really in the regulatory space, but if something NLP-related becomes active, I can probably loop people in.

Even simpler than NLP is the idea of a "readability score" for prospectuses.  The goal would be to incentivize funds to write them in a way that doesn't trip up investors - or guide casual investors away from complex products.

**Comment by mvanbuskirk** [comment]
Here

**Comment by ericaddy1** [comment]
Hello

**Comment by RichardWagener365** [comment]
Hi

**Comment by mcleo-d** [comment]
> Howdy!
> 
> I'm not really in the regulatory space, but if something NLP-related becomes active, I can probably loop people in.
> 
> Even simpler than NLP is the idea of a "readability score" for prospectuses. The goal would be to incentivize funds to write them in a way that doesn't trip up investors - or guide casual investors away from complex products.

Thanks for your comment @alvin-c-shih 👍  

I'll make sure  @ianhollowbread, @DavidVtFreshAIR, @agitana and @toshaellison are aware of your suggestion.

James.

**Comment by alvin-c-shih** [comment]
I guess I'll add that I was on a team for FINRA's Buildathon 2019 at MIT's Media Lab that was working on the theme of "Senior Investor Protection".  Readability score was the first part.  The second part was something that helped flag financial jargon / trap door language that increased risk or allowed deviation from the main strategy.  This might be workable across web sites as a browser plugin.
