### ISSUE TITLE
May 13th 2021 - Regulation Innovation SIG off-schedule meeting: "FDC3 for RegTech" Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/open-regtech-sig#27]
# Regulation Innovation SIG off-schedule meeting: FDC3 for RegTech
## Date
May 13 2021- 12:30pm EST / 5:30pm GMT

## Untracked attendees
- Sarah Sinclair / Change Gap
- James McLeod / FINOS
- Ian Hollowbread / ING
- Graeme Wynn / Acin
- Joe Robinson / Hummingbird
- Stephen Goldbaum / Morgan Stanley
- Trevor Hunt 

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Discussion between the FDC3 community (leading the FINOS FDC3 project delivering an open interoperability standard for the financial desktop) and those in our community focused on reg and regtech. The ambition is to extend the FDC3 standard across Regtech with participation from technology/platform vendors and financial institutions following the model established by FDC3 where the protocols are in production use and solving a number of challenges around interoperability.
              **Notes from the meeting:**        
              - Riko Eksteen provided an overview of FDC3 including the business value, technical value, and an example of how FDC3 can provide interoperability on a trader desktop. He also briefly reviewed core elements of the standard including App Directory, Intents, Context Data and API.       
              - Ian Hollowbread shared a demo of work done showing interoperability between multiple systems providing information about a single regulation, MiFID II in the example. This makes it much easier for compliance officers to leverage the value of multiple systems more seamlessly. FDC3 already provided value in this work and could be even more valuable with extensions specifically targeted at regtech.
              - The group discussed the value of establishing specific regtech uses cases ([like FDC3 did originally](https://fdc3.finos.org/docs/use-cases/overview)) to drive specific areas of development. It was suggested that a working group be established to do this.      
- [x] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ] Identify participants to draft use cases relevant to FDC3 for RegTech (please comment if you are interested)
- [ ] Action 2
- [ ] ...

### WebEx info: FDC3 for RegTech: exploratory meeting
- Thursday, May 13, 2021 12:30 pm | 1 hour | (UTC-04:00) Eastern Time (US & Canada)
- Meeting link: https://finos.webex.com/finos/j.php?MTID=md56c43c5c315470ddb9245ff7130f296
    - Meeting number: 127 855 4206
    - Password: YaVvqfjr758
- Join by video system: Dial 1278554206@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
- Join by phone:  +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 855 4206

**Comment by agitana** [comment]
hi

**Comment by mvanbuskirk** [comment]
Here

**Comment by kriswest** [comment]
here 🚀

**Comment by toshaellison** [comment]
Here (Tosha Ellison, FINOS)

**Comment by lspiro-Tick42** [comment]
Leslie Glue42

**Comment by mikakayf** [comment]
Mike here...

**Comment by jgavronsky** [comment]
Jane Gavronsky here

**Comment by Ivan-Radovanovic** [comment]
😊 hello there

**Comment by rikoe** [comment]
here

**Comment by mikakayf** [comment]
Mike O'Keeffe from Corlytics = mikakayf
