### ISSUE TITLE
May 18th 2021 - Regulation Innovation SIG off-schedule meeting: "Regulatory Taxonomy and Ontology Development" Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/open-regtech-sig#28]
# Regulation Innovation SIG
## Date
May 18 2021 - 12pm EST / 5pm GMT

## Untracked attendees
- Anand Satchit / Wells Fargo
- Eric Addy / My Compliance Centre
- David Ehrich / AIR
- Ian Hollowbread / ING
- Li Ann Wong
- Nicolas Decouttere / Regnosys
- Nils Cluzel / Braithwate
- Richard Wagener / Codethink
- Rob Thickett / Building Societies Association

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [[x] Discuss the proposal of a ["Regulatory Taxonomy and Ontology Development" project](https://github.com/finos/open-regtech-sig/blob/master/resources/demo-summaries.md#regulatory-taxonomy-and-ontology-development) - James Nicholls & Sarah Sinclair 
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made & Action Items
- [ ] Decision 1

### WebEx info
- https://finos.webex.com/finos/j.php?MTID=mc488c8cf375443c650ebef0cc4d0fdb2
- Meeting number: 127 253 0260
- Password: 6t7KJrZhh8z
- Join by video system: Dial 1272530260@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
- Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 253 0260

**Comment by agitana** [comment]
hi!

**Comment by TLATER** [comment]
o/

**Comment by toshaellison** [comment]
Here (Tosha Ellison, FINOS)

**Comment by ericaddy1** [comment]
Hello

**Comment by RichardWagener365** [comment]
Hi - Richard Wagener from Codethink

**Comment by jgavronsky** [comment]
Jane here
