### ISSUE TITLE
Jul 6th 2021 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/open-regtech-sig#32]
# Regulation Innovation SIG
## Date
Jul 06 2021 - 12pm EST / 5pm GMT

## Untracked attendees
- Sabrina del Prete / Korelabs
- Sarah Sinclair / Change Gap
- David Ehrich / AIR
- Richard Wagener / Codethink
- James Farquhar / Korelabs
- Tosha Ellison / FINOS
- Ian Hollowbread / ING
- Ian Purvis / Openfin
- Angelo Ovidi / Korelabs
- Nicolas Decouttere / Regnosys

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes - _June 1st meeting minutes were approved_
- [x] Regulatory Taxonomy and Ontology: progress update - Sarah Sinclair & James Nicholls
- [x] WikiKore: introduction - Sabrina del Prete 
- [x] AOB, Q&A & Adjourn (5mins)

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=mc39f602c94618d58437eac6707b6b5ab
- Meeting number: 127 988 1411
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 988 1411

**Comment by Ivan-Radovanovic** [comment]
hello everyone

**Comment by TLATER** [comment]
o/

**Comment by agitana** [comment]
hi

**Comment by pbouda** [comment]
hello

**Comment by jgavronsky** [comment]
Jane here

**Comment by Harriswe7** [comment]
Hello, Wendy here.

**Comment by nilscluzel** [comment]
Hi

**Comment by stephengoldbaum** [comment]
hi

**Comment by aamend** [comment]
Have you come across the [FIRE data model](https://suade.org/fire/manifesto/) for defining a common taxonomy in the transmission of granular data between regulatory systems in finance? Is there an overlap with what we want to standardize here?

**Comment by Taniem100** [comment]
Hi - Taniem here

**Comment by brooklynrob** [comment]
Hello
