### ISSUE TITLE
Oct 12th 2021 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/open-regtech-sig#35]
# Regulation Innovation SIG
## Date
Oct 12 2021 - 12pm EST / 5pm GMT

## Untracked attendees
- David Ehrich (AIR)
- James Nicholls (Braithwate)
- Julia Ritter (FINOS)
- Ian Hollowbread (ING)
- Nicolas Decouttere 
- Randy Repka (AIR)
- Ray Fung (Citi)
- Richard Wagener (Codethink)
- Sarah Sinclair (Change Gap)
- Stephen Goldbaum (Morgan Stanley)

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve [September 14th meeting minutes](https://github.com/finos/open-regtech-sig/issues/34)
- [x] Explainable AI/ML - Jeremy Bennett & William Jones, Embecosm (20 minutes)
- [x] Regulatory Taxonomy and Ontology Development project update - Taniem Choudhoury (Deutsche Bank), Sarah Sinclair (Change Gap), James Nicholls (Braithwate). (See their [presentation](https://www.youtube.com/watch?v=cFU-cyYCcec&t=7s) at Open Source Strategy London, October 5th 2021) (15 minutes)
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=m32d2a1c8dc93ee6d3d6caa2b2e8d12a6 
- Meeting number:  2702 047 3887
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 27020473887@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 2702 047 3887

**Comment by RichardWagener365** [comment]
Hi

**Comment by jeremybennett** [comment]
Hi, Jeremy Bennett, Will Jones and Ian Loveless from Embecosm attending

**Comment by hisergiorojas** [comment]
Hello

**Comment by cook-nick** [comment]
Hi. Nick Cook (with AIR). Joined a few minutes late - at 1710 - with apologies.
