### ISSUE TITLE
Nov 2nd 2021 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/open-regtech-sig#36]
# Regulation Innovation SIG
## Date
Nov 2nd 2021 - 12pm EST / 4pm GMT

## Untracked attendees
- David Ehrich (AIR)
- Francois-Xavier Houard (SUSE)
- James Nicholls (Braithwate)
- Julia Ritter (FINOS)
- Keith Bear (Cambridge University)
- Lucian (Citi)
- Nicolas Decouttere
- Peter Bouda
- Randy Repka (AIR)

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve [October 12th meeting minutes](https://github.com/finos/open-regtech-sig/issues/35) - _meeting minutes were approved_
- [x] **[FINOS Open Source Strategy Forum](https://events.linuxfoundation.org/open-source-strategy-forum-new-york/)** New York, November 10th
    - [Keynote session, Sultan Meghji, Chief Innovation Officer, FDIC & Jo Ann Barefoot, CEO & Cofounder, Alliance for Innovative Regulation](https://events.linuxfoundation.org/open-source-strategy-forum-new-york/program/schedule/)
- [x] https://github.com/finos/open-source-readiness/discussions/9 - Jane Gavronsky, FINOS
- [ ] **Collaboration opportunities to address policies and regulations around the software development lifecycle** (SDLC). (Presented at a [FINOS DevOps Mutualization Special Interest Group (SIG)](https://github.com/finos/devops-mutualization#devops-mutualization-special-interest-group)) - Amol Shukla (@ashukla13), Morgan Stanley - 15 minutes
    - Many banks are investigating or implementing hands-free change deployment while still demonstrating conformance with regulatory controls and internal policies. The Automated Change Deployment working group has been setup to document how different FINOS member banks are enabling automated change deployment.
    - The [FINOS DevOps Mutualization Special Interest Group](https://github.com/finos/devops-mutualization#devops-mutualization-special-interest-group) welcomes the opportunity to collaborate with the Regulation Innovation SIG in opening a dialogue with the regulators during the creation and once the document has taken shape.
- [x] **Morphir as a tool to enable machine-readable regulation** (Attila Mihaly, Morgan Stanley; Stephen Goldbaum, Morgan Stanley; Francois-Xavier Houard, SUSE; Richard Wagener, Codethink) - 15 minutes
- [x] **Reg Taxonomy project update** (James Nicholls, Braithwate) - 5 minutes
    - Invitation to join the November 16th ad-hoc meeting to discuss the Reg Taxonomy project proposal. Meeting details available at https://github.com/finos/open-regtech-sig/issues/37 
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=m6be3cd5cdc56622e15e74fbd30e7253c
- Meeting number:  127 759 5114
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1277595114@finos.webex.com You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 759 5114

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by RichardWagener365** [comment]
Richard Wagener / Codethink

**Comment by jgavronsky** [comment]
Jane Gavronsky / FINOS

**Comment by anelledavis** [comment]
Ashley Nelle-Davis / Data Foundation

**Comment by mvanbuskirk** [comment]
Matt Van Buskirk - Hummingbird

**Comment by stephengoldbaum** [comment]
Stephen Goldbaum - Morgan Stanley

**Comment by ashukla13** [comment]
Amol Shukla - Morgan Stanley

**Comment by DavidVtFreshAIR** [comment]
David Ehrich - AIR (Alliance for Innovative Regulation)
