### ISSUE TITLE
March 1st 2022 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by agitana** [finos/open-regtech-sig#38]
# Regulation Innovation SIG
## Date
Mar 1 2022 - 12pm EST / 5pm GMT

## Untracked attendees
- Alex Khachaturian / FINRA
- Adi Rastogi / FINRA
- Afshin Atabaki / FINRA
- Attila Mihaly / Morgan Stanley
- Chris Raybould / RBC
- David Ehrich / AIR
- Haime Workie / FINRA
- Hazel Dowling / Corlytics
- Ian Hollowbread / ING
- James Nicholls / Braithwate
- Jeroen Vunderink / ING
- John Byrne / Corlytics
- Mark Scannel / Google
- Naomi Oosthuizen / ING
- Niek Delis / ING
- Peter Vissers / ING
- Ramesh Subramanyan / SMBC
- Robert Hooper / TD Securities
- Scott Kerr / Bank of Montreal
- Steve Marshall / Goldman Sachs
- Sarah Sinclair / Change Gap
- Sunny Ho / Bank of Montreal
- Suyash Chaudhary / RBC
- Vincent Schultinge / ING

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve [November 2nd, 2021](https://github.com/finos/open-regtech-sig/issues/36) and [November 16th, 2021](https://github.com/finos/open-regtech-sig/issues/37) meeting minutes
- [x] Introducing James McLeod (FINOS) as Reg SIG go-to person
- [x] FINRA presentation
- [ ] Reg Taxonomy project update - Sarah Sinclair
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=m6be3cd5cdc56622e15e74fbd30e7253c
- Meeting number:  127 759 5114
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 759 5114

**Comment by stephengoldbaum** [comment]
In addition to LCR, we've had requests to see what compliance regulations we could take up.

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by AttilaMihaly** [comment]
Hi

**Comment by anelledavis** [comment]
Hi - Ashley Nelle-Davis // Data Foundation

**Comment by gyehuda** [comment]
Hello (and note: my organization has blocked access to the WebEx chat. I was not aware that could happen, but now you know that is a possibility). Chatting is risky. I guess I'm living on the edge.

**Comment by agitana** [comment]
Hi! Aitana Myohl / FINOS

**Comment by jgavronsky** [comment]
Jane @ FINOS here

**Comment by NicDecouttere** [comment]
Hi all! Good to be here.

**Comment by mtronci** [comment]
hello from Mose@Google Cloud

**Comment by claudardele** [comment]
Hello from Claudia Ardeleanu @BMO

**Comment by mcleo-d** [comment]
Hi all 👋🏻  - I've just enabled GitHub Discussions on the Innovation Regulation GitHub Repo. Feel free to suggest topics and ask questions via the link pasted below ...

https://github.com/finos/open-regtech-sig/discussions
