### ISSUE TITLE
April 5th 2022 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-regtech-sig#40]
# Regulation Innovation SIG
## Date
Apr 5 2022 - 12pm EST / 5pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] In previous Regulation Innovation SIG meetings we had converged on the LCR for our initial pilot based on the fact that it is widely known, nicely sized, and has recently been updated so is relevant.  In this meeting we would like to confirm that decision and discuss ... 
  - LCR contribution being socialised on FINOS Community repository - https://github.com/finos/community/issues/177 
  - Pilot Planning 
  - SIG Involvement
  - Timelines
- [ ] https://github.com/finos/community/issues/179 - Proposal recently contributed for FINOS and wider socialisation - James Nicholls / Braithwate, Sarah Sinclair / Change Gap, Taniem Choudhury / Deutsche Bank
- [ ] Q&A : Follow up on FINRA presentation from #38. 
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=m6be3cd5cdc56622e15e74fbd30e7253c
- Meeting number:  127 759 5114
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 759 5114

**Comment by MichaelJordanP** [comment]
Michael J Pilgreen from BondCliQ

**Comment by stephengoldbaum** [comment]
Stephen Goldbaum from Morgan Stanley

**Comment by jgavronsky** [comment]
Jane @ FINOS here

**Comment by B-Wardrop** [comment]
Bob Wardrop from Cambridge Centre for Alternative Finance at Cambridge University

**Comment by grizzwolf** [comment]
Grizz from FINOS
