### ISSUE TITLE
May 3rd 2022 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-regtech-sig#41]
# Regulation Innovation SIG
## Date
May 3 2022 - 12pm EST / 5pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] https://github.com/finos/community/issues/177
- [x] https://github.com/finos/community/issues/179
- [x] https://github.com/finos/community/issues/183
- [x] RegTech themed NYC FINOS Meetup in the planning for June 8th 2022
  - Stephen Goldbaum (Morgan Stanley), Paul Childerhose (Canadian RegTech Association), Google NYC Team Potential Speakers
  - Keep and eye out for an announcement
  - Please feedback
- [x] AOB, Q&A & Adjourn (5mins)
  - [x] Morphir / REGnosys tech sprint recap and potential FINOS community demo

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=m6be3cd5cdc56622e15e74fbd30e7253c
- Meeting number:  127 759 5114
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 759 5114

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by AttilaMihaly** [comment]
Hello

**Comment by anelledavis** [comment]
Hi - here!

**Comment by sarahsinclair** [comment]
hello

**Comment by dehrich123** [comment]
hello
