### ISSUE TITLE
July 5th 2022 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-regtech-sig#43]
# Regulation Innovation SIG
## Date
July 5 2022 - 12pm EST / 5pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Update from FINOS Reg Theme Meetup
  - https://github.com/finos/community/issues/194
- [ ] Update and Next Steps : 
  - https://github.com/finos/community/issues/177 
  - https://github.com/finos/community/issues/179
  - https://github.com/finos/community/issues/195
  - https://github.com/finos/community/issues/197
- [ ] AOB, Q&A & Adjourn (5mins)

## Open Source in Finance Forum London, July 13th 2022

Register below for the FINOS [Open Source in Finance Forum](https://events.linuxfoundation.org/open-source-finance-forum-london/) in London on July 13th 2022 👾💥

Open Source in Finance Forum is the only conference dedicated to driving collaboration and innovation in financial services through open source software and standards.

We bring together experts across financial services, technology, and open source to engage our community in stimulating and thought-provoking conversations about how to best (and safely) leverage open source software to solve industry challenges.

FINOS members employees are eligible to receive complimentary registration as part of their company’s membership. Please email [osff@finos.org](mailto:osff@finos.org) to request the Finos Member access code.

Register and find out more 👉🏻 https://events.linuxfoundation.org/open-source-finance-forum-london/

<a href="https://events.linuxfoundation.org/open-source-finance-forum-london/"><img src="https://user-images.githubusercontent.com/6029572/171230930-a68f99a3-ac8d-4738-8054-87af2d45b544.png" width="85%" /></a>

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=m6be3cd5cdc56622e15e74fbd30e7253c
- Meeting number:  127 759 5114
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 759 5114

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by lolabeis** [comment]
Hi

**Comment by stephengoldbaum** [comment]
Hello from Morgan Stanley

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by sndpkumar14** [comment]
Hello, this is Sandeep/ Synechron FinLabs

**Comment by mcleo-d** [comment]
Hi 🐱

**Comment by DavidVtFreshAIR** [comment]
david ehrich - AIR (Alliance for Innovative Regulation)

**Comment by SolarDesalination** [comment]
Hello, Kevin Morris

**Comment by RichardWagener365** [comment]
Hi - Codethink

**Comment by jgavronsky** [comment]
Jane / FINOS

**Comment by alexandrelealbess** [comment]
Hello, Alexandre | Legalbot
