### ISSUE TITLE
February 7th 2023 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-regtech-sig#49]
# Regulation Innovation SIG
## Date
February 7 2023 - 12pm EST / 5pm GMT

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=m6be3cd5cdc56622e15e74fbd30e7253c
- Meeting number:  127 759 5114
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 759 5114

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Compliant Financial Infrastructure - Introduction and call for requirements - @abdullahgarcia, @AdrianHammond - JPMC and Red Hat
- [ ] Confirmation of Payee (CoP) - UK Payments Initiative - Tim Norman - Synechron Payments
- [ ] Making the case for a FINOS Payments Special Interest Group - Andrew Duckett and Andy Smith - Discover 

**Confirmation of Payee**
The Payment Systems Regulator (PSR) has confirmed its plans that will see around 400 more financial firms provide the name checking service, Confirmation of Payee (CoP). CoP is a service that checks account and reference details when CHAPS, Faster Payment or standing order is setup. This helps to make sure payment aren’t sent to the wrong account by mistake and will reduce fraud. CoP needs to be developed to provide Customers of the UK payments industry with a way to check the name on the Account Details of the person/entity they wish to pay.

**BACKGROUND**
CoP is an overlay service that checks that the Account Name provided by a Payer corresponds, to an acceptable level, with the Account Name identified by the CoP Responder with the Account Details the Payer has supplied. CoP aims to give the Customer more control and more certain outcomes when they make a Payment by providing them with assurance regarding the name on the account, they wish to make a Payment to. In particular, it aims to provide consumers with a tool which can be used to avoid making misdirected payments.

**OBJECTIVE**
One of the key objectives of CoP is to reduce the incidences of misdirected payments; in particular, “Authorized Push Payment” fraud which is of significant detriment and a concern to Customers in the UK payments market. Amongst other things, CoP will seek to substantially reduce the volume of payments that are fraudulently diverted.

Link to PSR ……………… https://www.psr.org.uk/news-and-updates/latest-news/news/psr-directs-400-firms-to-introduce-the-payment-protection-measure-confirmation-of-payee/

- [ ] https://github.com/finos/open-regtech-sig/issues/50 by @jgavronsky 
- [ ] Appetite for increasing SIG meeting cadence to 2x meetings per month
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=m6be3cd5cdc56622e15e74fbd30e7253c
- Meeting number:  127 759 5114
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 759 5114

**Comment by AdrianHammond** [comment]
Hi All 😄

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by eddie-knight** [comment]
:wave: :shipit:

**Comment by andybs** [comment]
Andy Smith @ Discover

**Comment by yulleyi** [comment]
Hello!

**Comment by anelledavis** [comment]
Ashley Nelle-Davis @ Data Foundation

**Comment by haggyj** [comment]
Hi 👋🏻 Jonathan Haggarty @ NatWest

**Comment by abdullahgarcia** [comment]
¡Hola!

**Comment by Julia-Ritter** [comment]
Julia / FINOS
