### ISSUE TITLE
December 05, 2023 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/open-regtech-sig#64]
# Regulation Innovation SIG
## Date
December 05 2023 - 12pm EST / 5pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
-  https://github.com/finos/open-regtech-sig/issues/59
- [ ] ESG hackathon and next steps
- [x] [Women in RegTech New York](https://www.linkedin.com/company/women-in-regtech-new-york?trk=public_post-text) RegRoundtable Luncheon to wrap up 2023!
- [ ] 1. Inventory of upcoming regulations across domains (Pre-Trade, Post, Trade, ESG, Capital etc.) 
- Can we maintain one centrally and distribute to members?
- We can plan for sharing commentaries and regular information sessions on upcoming regulations based on interest
- [ ] 2. Post-Trade regulation compliance: stories from the field (RI)
Survey members on priorities and willingness to work on defining rules and data models for the following upcoming regulations:
-   EMIR Refit - 2024
-   MIFID TR  Changes  - 2025
-   HKMA  Rewrite - 2025
-   US Securities Lending Markets - 2025
-   Others (UPI) etc.
We are missing a lot of regulations and we should ask other members if they have a comprehensive list
- [ ] 3. T+1 reporting Requirements: a case for collaborative component development (RI)
- Use of CDM for T+1
- How does CDM made it easy to model and report trade events intraday?
- Collateral and margin reporting
 - Data Controls for T+1
- [ ] 4. Overview of DRR and progress made on CFTC and EMIR - We should ask ISDA if they can share an update.
- [ ] 5. BCBS 239 Controls Standards and Trends – We can ask one of the consulting firms to speak about them. I  know folks at both EY& Deloitte who will be happy to present. All upcoming ESG Regulations are complying with these Standards. Having a list of Critical Data Elements (CDE’s) agreed for each regulation will help members maintain a consistent data control environment.
- [ ] 6. Prescriptions for data dictionaries and data models for Reg. Reporting use cases – Is there an appetite to maintain these centrally. We are doing this with CDM for Post-Trade, can we expand to other domains?6 
- [ ] 7. Data Strategy (latest trends) – Data products etc. (some of our consulting  & technology partners can provide regular updates)
- [ ] 8. Cloud Concentration risks for regulatory reporting
- [ ] AOB, Q&A & Adjourn (5mins)

## Meeting Minutes

Key points highlighted:
- Involvement of Morgan Stanley and Goldman Sachs: Both institutions are actively participating in open-source initiatives.
- The RegTechCouncil recently incorporated, with a focus on post-trade and pre-trade areas identified during FINOS events in London and NY.

Agenda Item - Inventory of Upcoming Regulations: 
- The need for a centralized inventory of upcoming regulations across domains (Pre-Trade, Post-Trade, ESG, Capital, etc.) was discussed. The goal is to establish a gold standard and create an API that supports banks, fintech, and regtech organizations by providing interpretations and use cases.
- Understanding Regulators' Needs: Emphasized the need for understanding the different sources, formality levels, and use cases regulators employ to facilitate a tailored response.
- Central Repository: The proposal to maintain a central repository of upcoming regulations by domains, with interest levels across member organizations, was discussed. The framework would be documented and maintained as part of FINOS.

Agenda Item - Use of CDM T+1 Reporting Requirements:
-  A case for collaborative component development was discussed, and plans were made to involve ISDA partners in future meetings as the DRR project was identified as a good use case.

Agenda Item - BCBS 239 Controls Standards and Trends:
- Plan to dedicate a session next year to this topic, with input from E&Y and Deloitte.

Stakeholder Prioritization: 
- Everyone to take the discussed topics back to stakeholders and identify items to prioritize. 
Building a Calendar:  
- Discussions on building a calendar to publish to stakeholders, compliance experts, and regulators for feedback.

## Action Items
- [ ] Establishment of Central Repository:
   - [ ]   Establish a central repository of all upcoming regulations by domains with interest levels across member organizations.
   - [ ]  Document and maintain this framework as part of FINOS.
- [ ] Use of CDM T+1 Reporting Requirements: 
   - [ ]  Reach out to ISDA team and schedule something for January's session.
- [ ] BCBS 239 Controls Standards and Trends: 
   - [ ]   Dedicate a session next year to BCBS 239 Controls Standards and Trends.
   - [ ]  Have EY and Deloitte present early next year.
- [ ] Prioritization and Stakeholder Engagement:**
   - [ ]  Everyone to take the list of initiatives back to stakeholders and to establish specific urgencies from the community regarding regulations and prioritize accordingly.
- [ ] Building a Calendar:
   - [ ]  Build a calendar to publish it to stakeholders, compliance experts, and registry experts for feedback. 

### Join Zoom Meeting
Join Zoom Meeting:
https://zoom.us/j/95819415471?pwd=VmxmeExMcXJFZWs4OGtnTXBiWnVHdz09
Meeting ID: 958 1941 5471
Passcode: 915672
Find your local number: https://zoom.us/u/acoFmoLAFE

**Comment by iansloyan** [comment]
Ian Sloyan - South Cardinal Advisors

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by tomhealey-icma** [comment]
Tom Healey/ICMA

**Comment by stephengoldbaum** [comment]
Stephen Goldbaum @ Morgan Stanley

**Comment by AndrewOConnor1** [comment]
Andrew O'Connor @ Synechron Consulting

**Comment by sudhendu-das** [comment]
Sudhendu Das, @ Citi, sudhendu-das

:-)

**Comment by martinudy** [comment]
Martin Udy Bank of England

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys
