### ISSUE TITLE
January 16th, 2024 - Regulation Innovation SIG Meeting Minutes 

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/open-regtech-sig#65]
- # Regulation Innovation SIG

## Date
January 16th, 2024 - 12pm EST / 5pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf)
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
   -  https://github.com/finos/open-regtech-sig/issues/64
- [x] Project idea: T+1 Settlement: SSI template build and potential digital authentication, FMSB Workstream. Presenter: Ffion Acland, Goldman Sachs
- [x] New project proposal: ESG Data standardization. Presenter: PJ Di Giammarino, JWG Group
- [ ] AOB, Q&A & Adjourn (5mins)

## Meeting Minutes

- Develop an open-source solution to enhance manual trade processes, offering a middle ground between existing digital platforms and manual methods.
- FMSB facilitates collaboration without imposing rules; focuses on providing tools and solutions.
- 25-40% of trades still manual, attributed to factors like client preferences and perceived inadequacy of existing vendor 
-  Authentication, especially time-consuming, identified as a significant challenge in settlement processes.
- Utilize FINOS tools to build models, digitize templates for an open-source solution, and improve authentication in settlement instructions.
-  HSBC, JP Morgan, Barclays, and RBC express interest in the project; discussion on their active role in FMSB.
- Discussion on the potential integration of Legal Entity Identifiers (LEIs) in settlement instructions for improved identification.
-  Consideration of forming working groups to contribute to the development of the proposed open-source solution.
- Explore integration with the CDM framework; follow-up discussions among key participants to determine feasibility and requirements.

## Action Items

- [ ] Follow-Up on CDM Integration
- [ ] Working Group Formation 
   - [ ] Proposal to form a working group to collaborate on the development and implementation of the solution.
- [ ] LEI Integration Discussion
- [ ] ESG Project Investment Planning:
   - [ ] Develop a plan for the anticipated investment in the ESG project, outlining key milestones and resource requirements.
- [ ] Reach out to potential participants for input and collaboration, ensuring diverse representation from the industry.
Follow-Up on Technical Challenges:
- [ ] Continue discussions on overcoming technical challenges related to Bcbs 2, 3, 9 and explore potential solutions.
- [ ] Form a collaborative effort to contribute to the development of the new XBRL schema for ESG data.
- [ ] Regularly review progress against the established timeline and adjust as needed.

### Join Zoom Meeting
Join Zoom Meeting:
https://zoom.us/j/95819415471?pwd=VmxmeExMcXJFZWs4OGtnTXBiWnVHdz09
Meeting ID: 958 1941 5471
Passcode: 915672
Find your local number: https://zoom.us/u/acoFmoLAFE

**Comment by jgavronsky** [comment]
Jane / FINOS here

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by ffionwiggins** [comment]
Ffion / GS

**Comment by RobReeveLexTego** [comment]
Rob Reeve - LexTego

**Comment by stephengoldbaum** [comment]
Stephen Goldbaum @ Morgan Stanley

**Comment by sarahsinclair** [comment]
Sarah Sinclair - Change Gap

**Comment by anelledavis** [comment]
Ashley Nelle-Davis // Data Foundation

**Comment by PJDiGi** [comment]
PJ Di Giammarino, JWG

**Comment by martinudy** [comment]
Martin Udy Bank of England

**Comment by desipops** [comment]
Desi Popova @ Goldman Sachs

**Comment by sarahsinclair** [comment]
Sarah Sinclair Change Gap
________________________________

**Comment by Perelmuter** [comment]
Rimma Perelmuter/FINOS
