### ISSUE TITLE
February 13th, 2024 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/open-regtech-sig#66]
# Regulation Innovation SIG
## Date
February 13th, 2024 - 12pm EST / 5pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
   - [x] https://github.com/finos/open-regtech-sig/issues/65
- [x]  ISDA DRR Presentation - David Shone, ISDA
   - [x] [DRROverview.pdf](https://github.com/finos/open-regtech-sig/files/14267773/DRROverview.pdf)
- [x]  CDM for the Buy Side - Emmanuel Geinoz, Pictet
- [x] AOB, Q&A & Adjourn (5mins)

## Meeting Minutes

Benefits of CDM and DRR:
- Standardized representation of trade events and contracts, reducing complexity and inconsistencies.
- Increased efficiency and reduced cost of regulatory reporting.
- Improved interoperability between systems and platforms.
- Ability to adapt to future regulatory changes with less effort.

Call to Action:
- The industry needs to collaborate and share best practices for CDM and CRR adoption.
- More focus on quantifying the business benefits of CDM and DRR.
- Develop resources and tools to support implementation.
- Encourage regulators to embrace CDM and DRR in their rule making.

## Action Items

- [x] FINOS to survey to gauge industry interest and understanding of CDM and DRR.
- [x] Organize workshops and hackathons to promote CDM and DRR adoption.
- [ ] Develop case studies and white papers highlighting the benefits of CDM and DRR.
- [ ] Advocate for regulatory support for CDM and DRR.

### Join Zoom Meeting
https://zoom.us/j/95819415471?pwd=VmxmeExMcXJFZWs4OGtnTXBiWnVHdz09
- Meeting ID: 958 1941 5471
- Passcode: 915672
- Find your local number: https://zoom.us/u/acoFmoLAFE

**Comment by tabi5h** [comment]
tabish ahmed / ISDA

**Comment by martinudy** [comment]
Martin Udy Bank of England

**Comment by sndpkumar14** [comment]
Sandeep Kumar, Synechron/FinLabs

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by dshoneisda** [comment]
David Shone/ISDA

**Comment by jgavronsky** [comment]
Jane / FINOS

**Comment by Perelmuter** [comment]
Rimma Perelmuter/FINOS

**Comment by kannan2024** [comment]
Kannan Rajagopal / Synechron

**Comment by ffionwiggins** [comment]
Ffion / GS

**Comment by apetroni** [comment]
Alessandro Petroni / Independent Advisor
