### ISSUE TITLE
March, 5th 2024 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by eteridvalishvili** [finos/open-regtech-sig#67]
# Regulation Innovation SIG
## Date
MMM DD YYYY - 12pm EST / 5pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
   - [x] https://github.com/finos/open-regtech-sig/issues/66
- [x] 1. [White House AI Executive Order](https://www.whitehouse.gov/briefing-room/statements-releases/2023/10/30/fact-sheet-president-biden-issues-executive-order-on-safe-secure-and-trustworthy-artificial-intelligence/): Implications for FS - Ian Sloyan
- [x]  2. ISDA DRR Reflections and Feedback from [February 13th Meeting](https://github.com/finos/open-regtech-sig/issues/66) - Ian Sloyan
- [x]  3. [Regulation Innovation and FO SIG Survey Questions ](https://www.research.net/r/JXC292Q)
- [x] AOB, Q&A & Adjourn (5mins)

## Meeting Minutes

**Agenda Item: White House AI Executive Order:**

- Ian Sloyan presented key points from the White House Executive Order related to AI.
- Discussion included implications for financial market infrastructures and data privacy.

**Formation of AI Readiness Special Interest Group:**
- Jane Gavronsky announced the formation of an AI Readiness SIG to help firms with AI compliance.
- Collaboration between SIGs was suggested for comprehensive coverage of AI-related topics.

**Open Floor for Discussion:**
- Participants were invited to share thoughts on the DRR and related presentations.
- Questions about accessing the presentation slides, which were to be shared through GitHub.
- Leo mentioned the availability of presentations from the CDM showcase, potentially shared by organizers.
- Eteri Dvalishvili provided an overview of the FINOS Regulatory Innovation and Financial Objects Questionnaire.
- Jane emphasized the importance of feedback to curate relevant topics for future meetings.

## Action Items
- [x] Participants to distribute the FINOS Regulatory Innovation and Financial Objects Questionnaire to relevant colleagues and networks.
- [x] Ian to share presentation slides via GitHub for wider access.
- [x] Interested members to register their interest in the AI Readiness SIG and provide input for future discussions.

### Join Zoom Meeting
https://zoom.us/j/95819415471?pwd=VmxmeExMcXJFZWs4OGtnTXBiWnVHdz09
- Meeting ID: 958 1941 5471
- Passcode: 915672
- Find your local number: https://zoom.us/u/acoFmoLAFE

**Comment by jgavronsky** [comment]
Jane / FINOS

**Comment by martinudy** [comment]
Martin Udy / Bank of England

**Comment by lolabeis** [comment]
Leo Labeis / REGnosys

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by anelledavis** [comment]
Ashley Nelle-Davis / Data Foundation

**Comment by noelmcloughlin** [comment]
Noel McLoughlin / TD

**Comment by ffionwiggins** [comment]
Ffion Acland / GS

**Comment by desipops** [comment]
Desi Popova/GS

**Comment by zeal-somani** [comment]
Zeal S / JupiterOne - I have newly joined this SIG
